[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"

# [[redirects]]
# from = "https://avadhoot.pages.dev/"
# to = "https://news.avadhoot.me/"
# status = 301
# force = true