[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"

[[redirects]]
from = "https://hugo-narrow.netlify.app/"
to = "https://blog.avadhoot.me/"
status = 301
force = true